version: '3'

services:
  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: sf_main
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: Asia/Tokyo
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql

  flask-sf:
    build: ./flask-sf
    container_name: flask-sf
    ports:
      - 5000:5000
    tty: true
    environment:
      FLASK_APP: main.py
      FLASK_ENV: development

    volumes:
      - ./flask-sf:/flask
    
    command: flask run --host=0.0.0.0
